# spring
spring:
  # mysql
  datasource:
    druid:
      url: jdbc:mysql://120.78.159.117:3306/crm?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      # 数据库密码加密，通过 cn.wolfcode.edums.core.util.DruidDatasourcePasswordUtil.main 方法对密码进行加密，获取密文密码与公钥
      password: DI5chIhW1Da8jCRoIgwM4Ewexui2p2p+1hvxQMu5VJ5eKgz+WePqxG3bSeezLbPnCDVfU7LR3Op1W6w7t0516w==
      initial-size: 10
      max-active: 200
      connection-properties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIdXEBejL7MMDbTcX7CNmtjPbeT6e0EcwLau9f7jP7kPF1a0Z53ZHSIyHNeJGwSuMG9EZcTZpM67h71aeDDOkxUCAwEAAQ==
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤格式
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      statViewServlet:
        enabled: true
        loginUsername: druid
        loginPassword: o982uue9h3r89
        url-pattern: /dstat/*
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        config:
          enabled: true